env:
  ASPNETCORE_ENVIRONMENT: "Development"
  HTDC_TOKEN_RECEIVER_SENTRY_ENDPOINT: "https://b2d130c8da05465a84b57806fb566d56@sentry.dev.happytravel.com/28"
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "contour"
    contour.heptio.com/retry-on: "5xx"
    contour.heptio.com/num-retries: "5"
    contour.heptio.com/request-timeout: "15s"
    contour.heptio.com/per-try-timeout: "3000"
  hosts:
    - host: token-receiver.dev.happytravel.com
      paths: [/]

  tls: 
    - hosts:
        - token-receiver.dev.happytravel.com